### ISSUE TITLE
Packer 1.6.6 HCL vSphere WinRM Time out Windows 10

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vsphere#100]
_This issue was originally opened by @mrdanielmartins in https://github.com/hashicorp/packer/issues/10650 and has been migrated to this repository. The original issue description is below._

---
Hi Gang,

I have been using Packer1.5.5 with JSON and all works splendidly to build my Windows Server and Windows Workstation boxes. Monday, I decided I wanted to treat myself with version 1.6.6 HCL.

I am faced with this error repeatedly and have no way out:

`2021/02/17 13:13:36 packer-builder-vsphere-iso plugin: [INFO] Attempting WinRM connection...
2021/02/17 13:13:36 packer-builder-vsphere-iso plugin: [DEBUG] connecting to remote shell using WinRM
2021/02/17 13:13:36 packer-builder-vsphere-iso plugin: [ERROR] connection error: http response error: 401 - invalid content type
2021/02/17 13:13:36 packer-builder-vsphere-iso plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type`

I have verified my HCL, autounattend and PS files, and even attempted the stuff below but to no avail:
1. Set WinRM timeout to 60 minutes
2. Hard setting WinRM user and password statically and through variable
3. Setting WinRM insecure
4. Tried using Packer versions 1.6.5, 1.6.4 and 1.6.0

Relevant files of HCLs, PS1s and autounattend below. This is not the complete file and folder structure, as there isn't anything that would pertain to this issue.
[packer_github_issue.zip](https://github.com/hashicorp/packer/files/5996936/packer_github_issue.zip)

It seems to ignore the configured/explicitly set WinRM username and password? What do you think it could be?

Thank you all,

Daniel

**Comment by dbond007** [comment]
The files you have put up here have winrm timeout at 15m.
401 usually means invalid authentication.
Have you tried manually remoting in with powershell?

One thing that i have noticed (with server 2019) is winrm doesn't always start up the first time, now and then the system needs a reboot.

For my builds (server) i have used the ansible powershell script for enabling winrm: https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
from: https://docs.ansible.com/ansible/latest/user_guide/windows_setup.html
You can also look at my packer setup on my repo, changing the ISO and the autounattend should be all that is needed for Win 10.
