### ISSUE TITLE
stuck at Waiting for IP...

### ISSUE THREAD

**Issue by MikaelUrankar** [hashicorp/packer-plugin-vsphere#101]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
It doesn't get further than Waiting for IP...

#### Reproduction Steps
packer build .

### Plugin and Packer version
packer 1.7.4 and plugin 1.0.1

### Simplified Packer Buildfile
The one from the example folder triggers the issue.

### Operating system and Environment details
Any OS.

### Log Fragments and crash.log files
There are no relevant logs.

Regressed by https://github.com/hashicorp/packer/pull/9450
Reverting https://github.com/hashicorp/packer/commit/50b6c86b1c25b0fcd876a3746a4e491bd3279f86 fixes the issue.

**Comment by dbond007** [comment]
I just tested with my build, updated to 1.7.4 (was on 1.7.3) and added plugin version 1.0.1 and builds fine. Tested with Ubuntu 20.04.3 (just updated)
If you are just used the example in the folder, I wouldn't rely upon it working. When I started with packer, the examples rarely did. Could be I came up against the same problems you are, doing something wrong (haven't really looked at them again). But packer 1.7.4 and vsphere plugin 1.0.1 appear to me to be working (excluding a change needed in a script being run after updating to 20.04.3 from .2).

I am using vcenter 6.7u3g esxi 6.7 with openvm tools installed.

**Comment by MikaelUrankar** [comment]
Can you share a working example? My conf works fine with packer 1.6.0 and breaks after the aforementioned commit.

**Comment by dbond007** [comment]
https://github.com/dbond007/Packer working examples of centos, ubuntu, windows 2k19, rocky.
I just added in the plugin version for 1.0.1 in the ubuntu examples.
in ubuntu, 18.04 in there is broken and I haven't bother looking at it.
20.04 has a a script problem after just updating to 20.04.3, comment out lines 26 to 31 rightnow in "/etc/scripts/030-network.sh" which would revert the network interface name to predictable names (eth0 etc).

**Comment by MikaelUrankar** [comment]
There is the same issue already reported, https://github.com/hashicorp/packer-plugin-vsphere/issues/75
It's fixed by https://github.com/vmware/govmomi/issues/2509
...
