### ISSUE TITLE
vSphere-ISO Builder Type and preseed.cfg for Ubuntu 20.04

### ISSUE THREAD

**Issue by vesubramanian** [hashicorp/packer-plugin-vsphere#104]
I am referring the JSON for Ubuntu 16.04 and trying to build one for 20.04. However I am very new to Packer. Hence, I would really appreciate if you could please provide answers to my queries.
1. For your host attribute, you have provided "esxi-1.vsphere65.test". What actually is this host? I am not very sure.
2.  I am not sure about the [datastore1] and the name of the ISO for 20.04, below. Where do we get datastore1?
    "iso_paths": [
        "[datastore1] ISO/ubuntu-16.04.3-server-amd64.iso"
      ]
3. Below network adapters, there is a password? Which user's password is expected?
4. In preseed.cfg, which user's user name is referred to as jetbrains? Is it the root or a custom non root user?

**Comment by tenthirtyam** [comment]
@vesubramanian - did the above sufficiently answer your questions for issue closure?

Ryan

**Comment by tenthirtyam** [comment]
@nywilken and @azr - recommend closing as answered.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by nywilken** [comment]
Thanks @tenthirtyam closing as recommended.
