### ISSUE TITLE
Feature request: Adding vTPM for Windows 11 during build ESXi 7.0.2

### ISSUE THREAD

**Issue by ChrisDek** [hashicorp/packer-plugin-vsphere#108]
#### Description
Starting with build 22458 laste weekend Microsoft has started enforcing vTPM in virtual machines for Windows 11. So without a TPM it is not possible to install Windows 11.

#### Use Case(s)
All Windows 11 deployments need a TPM.  My workaround of power down VM, add vTPM in webgui, power on VM is not easily automated outside of packer, so it would be best to add the feature.

Windows Server 2022 currently does not need TPM, but future versions could.

#### Potential configuration

A new option in Hardware Configuration

vTPM (bool) - Enable vTPM for virtual machine. Defaults to false.

#### Potential References

Adding a vTPM from powerCLI can be done via New-VTpm -VM $VM

**Comment by ChrisDek** [comment]
Build 22000.194 which is expected to be the version that will be released on 05.10.2021 also enforces a TPM

**Comment by aronwk-aaron** [comment]
Bumping because I need this too.
Without it, Windows 11 will be the only thing we don't have fully automated

**Comment by ibeerens** [comment]
Windows 11 is today officially released so it would be great if you can add vTPM

**Comment by tenthirtyam** [comment]
While I completely agree with supporting Win11 and vTPM, this can be bypassed for lab environments by adding the following your the `autounattend.xml`.

```

<RunSynchronousCommand>
               <Order>2</Order>
               <!-- Bypass TPM 2.0 precheck. -->
               <Path>cmd /c reg add &quot;HKLM\SYSTEM\Setup\LabConfig&quot; /f /v BypassTPMCheck /t REG_DWORD /d 1</Path>
            </RunSynchronousCommand>			

```

**Comment by tenthirtyam** [comment]
Hi @VladRassokhin - are you planning to submit the pull request for your work at https://github.com/VladRassokhin/packer-plugin-vsphere/commit/f601c814b1ddc0c22e6551c3bc8f63c60605c46c on this feature?

Ryan

**Comment by tenthirtyam** [comment]
Thanks for submitting the PR @VladRassokhin!
