### ISSUE TITLE
Packer 1.7.5 with vSphere-iso 1.0.1 - HTTP_content available?

### ISSUE THREAD

**Issue by tlb1galaxy** [hashicorp/packer-plugin-vsphere#111]
Hello,
I am trying to get the '**http_content**' option to work by using the template function.  I have not been able to get this to work or even produce an error (local webserver comes up but no files ever populated).

I am able to get the '**http_directory**' option to work (but not what I want in the workflow).

In the Git docs ([vsphere-iso_docs](https://github.com/hashicorp/packer-plugin-vsphere/blob/main/docs/builders/vsphere-iso.mdx), there is no mention of '**http_content**'.
But the [main site](https://www.packer.io/docs/builders/vsphere/vsphere-iso) does.

So I just want to know if '**http_contect**' is a valid option with vShpere-iso builder v1.0.1 before I continue to troubleshoot my issue.
Thanks

**Comment by sestegra** [comment]
@tlb1galaxy `packer-plugin-vsphere-1.0.1` uses `packer-plugin-sdk v0.2.3` (see [go.mod](https://github.com/hashicorp/packer-plugin-vsphere/blob/v1.0.1/go.mod)).

The documentation is located in [packer-plugin-sdk](https://github.com/hashicorp/packer-plugin-sdk) project
See https://github.com/hashicorp/packer-plugin-sdk/blob/v0.2.3/cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/multistep/commonsteps/HTTPConfig-not-required.mdx

So, vSphere-iso 1.0.1 contains `http_content` parameter.

**Comment by tlb1galaxy** [comment]
Thanks for the confirmation.
I will try my code again with the 'http_content' option and verify the issue again for a bug report (if need be).
