### ISSUE TITLE
[vsphere-clone] How to use vm template in content library as source vm

### ISSUE THREAD

**Issue by huonguyenlt** [hashicorp/packer-plugin-vsphere#137]
I want to create vm from vm template which is in the content library. How do I provide full path of the vm template to the "template" in the clone configuration?

**Comment by iamjoos** [comment]
It doesn't seem to be supported yet, please see #43.

**Comment by tenthirtyam** [comment]
Existing enhancement.

Duplicate of #43.

cc @nywilken

**Comment by tenthirtyam** [comment]
Duplicate of #43
