### ISSUE TITLE
`vsphere-clone`: slash in vm name results in 'vm to clone not found'

### ISSUE THREAD

**Issue by lovetheguitar** [hashicorp/packer-plugin-vsphere#140]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview

I'm naming some vms automatically to branch name and commit sha.
This works, but only as long as there are no slashes in the branch name.

#### Reproduction Steps

Try to use any vm, whose name contains a slash, as the template vm to vsphere-clone.
==> vsphere-clone.from_base_win: Error finding vm to clone: vm 'base_win-feature/debug-02182c1f' not found

Although the vm exists and a slash seems to be an accepted character for vSphere.

### Plugin and Packer version

Packer v1.7.8
packer-plugin-vsphere_v1.0.2_x5.0_linux_amd64

### Operating system and Environment details

I'm using the official packer docker img.

### Log Fragments and crash.log files
==> vsphere-clone.from_base_win: Uploading packer344917133.iso to packer_cache/packer344917133.iso
==> vsphere-clone.from_base_win: Cloning VM...
==> vsphere-clone.from_base_win: Error finding vm to clone: vm 'base_win-feature/debug-02182c1f' not found
==> vsphere-clone.from_base_win: Step "StepCloneVM" failed

Thanks a lot for packer! 😄

**Comment by tenthirtyam** [comment]
The name would need to be escaped because vSphere and the plugin will see it as a literal path. %2F = /

**Comment by tenthirtyam** [comment]
The slash (`/`) character is a special character that is often used as a path separator in file systems. 

Additionally, in vSphere, slashes (`/`) in VM names are treated as inventory path separators for VMs - _folders, cluster, resource pool, datacenter_ - and is not advised.

```bash
/<datacenter-name>/vm/<folder_name>/<vm_name>
/sfo-dc01/vm/templates/ubuntu-2204-v1.5.0-rc
```

If you create a VM with a (`/`) in the name, the files will use `%2f` in datastore path and file names.

```bash
develop%2flinux-photon-5.0/develop%2flinux-photon-5.0-4e68e69a.hlog
develop%2flinux-photon-5.0/develop%2flinux-photon-5.0.nvram
develop%2flinux-photon-5.0/develop%2flinux-photon-5.0.vmdk
develop%2flinux-photon-5.0/develop%2flinux-photon-5.0.vmdk
develop%2flinux-photon-5.0/develop%2flinux-photon-5.0.vmsd
develop%2flinux-photon-5.0/develop%2flinux-photon-5.0.vmsd
develop%2flinux-photon-5.0/develop%2flinux-photon-5.0.vmx
```

Further to this, when exported, it will export the files to be in the following format replacing `%2f` with `_`:

```bash
develop_linux-photon-5.0.ovf
develop_linux-photon-5.0.mf
develop_linux-photon-5.0-1.vmdk
develop_linux-photon-5.0-2.nvram
```

In vSphere,  if you attempt to add this VM to the content library as an OVF Template, if will fail as it expects the `_` to be present and replace the `/` when packaging the OVA.

```bash
A general system error occurred: The import of library item 9766b00e-7a4c-4906-8a28-b24f5a58ac6f has failed. 

Reason: Error transferring file develop_linux-photon-5.0-1.vmdk from ds:///vmfs/volumes/5e23c68e-205e0956-fed3-4cd98f4a36d1/%2Fdevelop%252flinux-photon-5.0%2Fdevelop%252flinux-photon-5.0.vmdk. 

Reason: Error during transfer of ds:///vmfs/volumes/5e23c68e-205e0956-fed3-4cd98f4a36d1/%2Fdevelop%252flinux-photon-5.0%2Fdevelop%252flinux-photon-5.0.vmdk: File [local-ssd-01] develop/linux-photon-5.0/develop/ was not found.
```

Closing as **Not Planned**.

cc @nywilken
