### ISSUE TITLE
`vsphere-clone`: Cannot create VM with different disk size

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vsphere#141]
_This issue was originally opened by @huonguyenlt in https://github.com/hashicorp/packer/issues/11423 and has been migrated to this repository. The original issue description is below._

---
Is there a way to create a vm using vsphere-clone that change the disk size. For example, vm template has disk size 20gb. Now I want new created vm have disk size 30gb.
Below is what I have tried:

I created VM template with this storage config:
`storage {
      disk_size               =  20480
      disk_thin_provisioned   =  true
   }`
Next, I use vsphere-clone to create a vm from the vm template. I set storage config as follow:
`storage {
      disk_size               =  10480
      disk_thin_provisioned   =  true
   }`
I expected new vm storage has size of 30gb.
However, I was getting this error: `storage[0].'disk_controller_index' references an unknown disk controller`

**Comment by mikeschinkel** [comment]
I am having same issue.

**Comment by tenthirtyam** [comment]
For general questions, we recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for greater visibility.  The GitHub issue tracker is only watched by a small group of maintainers and collaborators and is typically reserved for bug reports and enhancement request. You will typically have more success finding assistance on the forum.

If you find the forum to be more helpful or if you've found the answer to your question elsewhere, please comment and close the issue. If there is no further activity on this question within the next 30 days it will be closed.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Marking this issue as closed. If this issue is reproducible with the latest version of the plugin, please create a new issue linking back to this one for added context. 

Thank you!
