### ISSUE TITLE
packer fails to import template to content library

### ISSUE THREAD

**Issue by Zypheros** [hashicorp/packer-plugin-vsphere#142]
#### Overview of the Issue
Packer fails when trying to import template to Content Library. The build has been tested with full administrator permissions.
Suspecting deprecated api as I have manually done this and it works fine with the template being created here.

Link to 7.0.2 documentation: https://developer.vmware.com/apis/vsphere-automation/latest/content/api/content/local-library/get/
Link to 7.0.0 documentation: https://developer.vmware.com/apis/vsphere-automation/v7.0U2-deprecated/content/rest/com/vmware/content/library/get/
#### Reproduction Steps
Build any template using the vsphere-iso builder and use the config_library_destination configuration.

### Packer Version
- 1.7.8

### Plugin Version and Builders 
 - 1.0.2

Please select the builder.
- [X] `vsphere-iso`
- [] `vsphere-clone`

### VMware vSphere Version
 - 7.0.2

### Guest Operating System
- Red Hat Enterprise Linux 8

### Simplified Packer Buildfile
https://gist.github.com/Zypheros/95814c91a28d2e62d61733ed04c2ee04

### Operating System and Environment Details
OS: docker ubuntu image pulled via gitlab pipeline.

### Log Fragments and `crash.log` Files
https://gist.github.com/Zypheros/5587c4a70445e68beb2d188ffbaa4ae0

**Comment by tenthirtyam** [comment]
I've not seen this issue occur in my [vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere) which uses the following to send all images to the content library as OVF.

```ccl
  // Template and Content Library Settings
  convert_to_template = var.common_template_conversion
  dynamic "content_library_destination" {
    for_each = var.common_content_library_name != null ? [1] : []
    content {
      library     = var.common_content_library_name
      ovf         = var.common_content_library_ovf
      destroy     = var.common_content_library_destroy
      skip_import = var.common_content_library_skip_import
    }
  }
```

Can you set `convert_to_template  = "false"` to `convert_to_template  = false` and retest?

Ryan

**Comment by tenthirtyam** [comment]
In addition, be sure that the user has Global Permissions as the Content Library sits higher in the hierarchy.

This is described in a recent pull request: https://github.com/hashicorp/packer-plugin-vsphere/pull/131

> "Global permissions **[are required](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-03B36057-B38C-479C-BD78-341CD83A0584.html)** for the content library based on the hierarchical inheritance of permissions. Once the custom vSphere role is created, assign **Global Permissions** in vSphere to the accounts or groups used for the Packer to vSphere integration, if using the content library."

Ryan

**Comment by Zypheros** [comment]
I dont have the `convert_to_template = false` parameter set anywhere in the code so it does default to false and the build does run when removing the content library config. I will try to tweak the permissions next, thanks.

Endre

**Comment by Zypheros** [comment]
Update: You were totally right with the permissions, it solved the problem. Thank you so much, and sorry for the trouble.
