### ISSUE TITLE
Does this plugin support unattended installation via non-HTTP sources?

### ISSUE THREAD

**Issue by synergiator** [hashicorp/packer-plugin-vsphere#148]
Imagine you want to provision configuration files for an unattended installation.

Typically you go for HTTP but if this not an option (or shouldn't be your first choice), what are possible alternatives?

Is USB support implemented in this plugin?

**Comment by tenthirtyam** [comment]
cd_content and floppy_content are options other that http_content.

**Comment by synergiator** [comment]
thx
