### ISSUE TITLE
[vsphere-iso] vmx_data_post argument documented but not implemented.

### ISSUE THREAD

**Issue by itayporezky** [hashicorp/packer-plugin-vsphere#164]
#### Overview of the Issue

Unable to use [vmx_data_post](https://www.packer.io/plugins/builders/vmware/iso#vmx_data_post)
in vsphere-iso
it appears to not be supported.

#### Reproduction Steps

Use build code below and run `packer init .`

### Packer Version
Packer v1.7.9

### Plugin Version and Builders

Please provide the plugin version.
1.0.3 but i tried older ones too

Please select the builder.
- [x] `vsphere-iso`
- [] `vsphere-clone`

### VMware vSphere Version
7.0.2 - but this is irrelevant

### Guest Operating System
Ubuntu 20.04 LTS x64 - but this is irrelevant

### Simplified Packer Buildfile

```
source "vsphere-iso" "linux-ubuntu-server" {
  vmx_data_post = {
    "uuid.bios" = "253e3755-0f3a-4d57-9240-d6e9fc69fcef",
    "uuid.action" = "create"
  }
}

build {
  sources = [
    "source.vsphere-iso.linux-ubuntu-server"]
 }
```

### Operating System and Environment Details

Ubuntu 18.04 - but this is irrelevant, i've tried running using packer on docker and native on linux.

### Log Fragments and `crash.log` Files

Copy above build file and try running `packer init .`
Error will show:
`An argument named "vmx_data_post" is not expected here.`

But this argument should be supported and is documented [here](https://www.packer.io/plugins/builders/vmware/iso#vmx_data_post)

**Comment by tenthirtyam** [comment]
The link you've provided is for the `vmware-iso` builder in the plugin, not the `vsphere-iso` builder in the plugin.

Your example shows that you are using `vsphere-iso`, but this option is not present in this builder.

Ryan

**Comment by itayporezky** [comment]
You're right, im sorry.
