### ISSUE TITLE
[vsphere-iso] "disk_thin_provisioned = true" -> does not working

### ISSUE THREAD

**Issue by TimUx** [hashicorp/packer-plugin-vsphere#166]
#### Overview of the Issue

When we create VMs via vsphere-iso plugin and define the disks as thin, ist will allways create "Thick Easer Zerod" Disks

#### Reproduction Steps

Create new VM with same hcl file

### Packer Version

1.7.5 and 1.7.10

### Plugin Version and Builders

Please provide the plugin version.

1.0.3 and 1.0.5

Please select the builder.

- [x] `vsphere-iso`
- [] `vsphere-clone`

### VMware vSphere Version

7.0.3.00300

### Guest Operating System

     - Ubuntu 20.04 LTS x64

### Simplified Packer Buildfile

` storage {
    disk_controller_index = 0
    disk_size             = 64
    disk_thin_provisioned = true
  }
  storage {
    disk_controller_index = 0
    disk_size             = 65664
    disk_thin_provisioned = true
  }
  storage {
    disk_controller_index = 1
    disk_size             = 262272
    disk_thin_provisioned = true
  }`
https://gist.github.com/TimUx/c536f2b89161c0bdd409c6ab30c46861

### Operating System and Environment Details

Ubuntu 20.4.3

### Log Fragments and `crash.log` Files

https://gist.github.com/TimUx/b2835a960dd5bd84f772993f1cec1ca2

**Comment by TimUx** [comment]
Hi, it seems to be an issue in vSphere with our Backend NFS Storage. 

I also can't create Thin Disks manually in a VM. 
I chose Thin but vSphere creates Thick ...

**Comment by tenthirtyam** [comment]
Is this still an environmental issue?

**Comment by tenthirtyam** [comment]
@nywilken - recommend closure based on originator's prior comment of an environment issue.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by nywilken** [comment]
Thanks @tenthirtyam. Closing as requested.
