### ISSUE TITLE
`vsphere-clone`:  Add support to destroy VM after successful build

### ISSUE THREAD

**Issue by supershal** [hashicorp/packer-plugin-vsphere#168]
I am using packer “vsphere-clone” build to create OVA in our vsphere test environments.
our automation creates new VM / template upon every Pull Requests.
I like to destroy the VM if it runs from test flows and convert it to template on other flows.

Also I am using “convert_to_template”=false when building images during test flows. This helps preventing template creation but the VM still stays on vsphere after successful run and I have to write additional scripts to destroy it manually. 

I like to configure the packer build such a way that it automatically delete the VM upon successful run too. 
is there such configuration already available for vsphere-clone ?

**NOTE:** I have asked the same question on packer community forum, but havent got any response yet so asking here. 
https://discuss.hashicorp.com/t/how-to-destroy-vsphere-vm-after-successful-packer-build-of-vsphere-clone-type

**Comment by tenthirtyam** [comment]
Convert ti enhancement similar to #180.

cc @nywilken 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by nywilken** [comment]
The PR #204 implements this functionality for the vsphere-iso builder. It is easy enough to extended the PR to account for both builders @tenthirtyam can you help push that forward?

**Comment by tenthirtyam** [comment]
Sure thing @nywilken - I'll discuss it with @paleloser.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by MrKeiKun** [comment]
@tenthirtyam 

any updates regarding this feature?

**Comment by tenthirtyam** [comment]
I've not had an opportunity to discuss incorporating this with @paleloser so there aren't any updates.

**Comment by dkasten79** [comment]
Any updates on this issue? I see that there is a pull request that has been open for 2 months now for adding the option and I could use this capability in some build processes so I don't have to use a PowerCLI script to tear down the VM. This would keep parity with how I am doing it with the vsphere-iso plugin.

**Comment by tenthirtyam** [comment]
I'll defer to @nywilken for a maintainer comment. I'm happy to review and test in the near term.

**Comment by nywilken** [comment]
Hi Folks, apologies for the hold up here. The team has been working through a number of priorities across plugins and Packer. So we are making our way to PRs and issues. I appreciate everyone keep tabs on the issue. The PR has been approved. I will merge it and release today. Cheers.
