### ISSUE TITLE
Add support for VBS (Virtualized Based Security) option

### ISSUE THREAD

**Issue by arjancool** [hashicorp/packer-plugin-vsphere#171]
Per v1.0.3 the VMware vSphere plugin has support for adding a vTPM device.
It would be great to add the VBS (Virtualized Based Security) option.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Adding the option to enable VBS in the VMware vSphere plugin.

#### Use Case(s)

VBS enabled Microsoft Servers enables the option to use a number of security solutions, including Credential Guard.

https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-vbs

**Comment by nywilken** [comment]
Thanks for calling out the duplication @robwesterby I'm going to append the original request as a comment to this thread and close so that it can be tracked on this issue. I will do the same for #190 as this issue has the most counts.

**Comment by nywilken** [comment]
Copying the description from the first issues related to this request in order to consolidate the threads. 

```
Please make the vSphere vim.vm.FlagInfo API available to the configuration file:
https://code.vmware.com/apis/358/vsphere/doc/vim.vm.FlagInfo.html

The vim.vm.ConfigSpec API is already available through configuration_parameters:
https://code.vmware.com/apis/358/vsphere/doc/vim.vm.ConfigSpec.html
Use Case(s)

Allows us to build VMs with active Virtualization-Based Security (vbsEnabled) and disk UUIDs (diskUuidEnabled). Allows the usage of the API in general.
Potential configuration

{
    "builders": [
        {
            "vim_vm_FlagInfo": {
                "diskUuidEnabled": true,
                "vbsEnabled": true,
                "vvtdEnabled": true
            }
        }
    ]
}
```

**Comment by nywilken** [comment]
The contents of https://github.com/hashicorp/packer-plugin-vsphere/issues/190 is related to this request.

**Comment by tenthirtyam** [comment]
Taking a quick look at this, the plugin would need to allow `VbsEnabled` (and perhaps `VvdtEnabled`) from `types.VirtualMachineFlagInfo` in `vmware/govmomi` - would assume use on currently supported versions (VBS added in 6.7).

This may require an additional step to be added, such as`StepFlagsInfo`. It may also require the addition of an additional function in the drive like `AddFlagOptions` or similar.

**Comment by powertim** [comment]
Hi, any update on this ?

**Comment by tenthirtyam** [comment]
I've not had time to investigate further.
