### ISSUE TITLE
vsphere-iso: could not find a supported CD ISO creation command

### ISSUE THREAD

**Issue by Sarahshee** [hashicorp/packer-plugin-vsphere#181]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

packer  build produces error

vsphere-iso: output will be in this color.

==> vsphere-iso: Creating CD disk...
Build 'vsphere-iso' errored after 888 milliseconds 672 microseconds: could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)

==> Wait completed after 888 milliseconds 727 microseconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)

==> Builds finished but no artifacts were created.
-sh-4.2$ clear

**Comment by tvories** [comment]
I have the exact same issue as @Beuteltiger171 on the docker image hashicorp/packer:1.8.0.  It works on my Mac, but when running this in a gitlab runner, I get the same `Failure: grafting failed` error

**Comment by CDKnightNASA** [comment]
Cygwin has "mkisofs" which is, apparently, a wrapper for genisoimage...But I'm wondering if it could work:

```$ mkisofs --version
mkisofs 2.01 is not what you see here. This line is only a fake for too clever
GUIs and other frontend applications. In fact, this program is:
genisoimage 1.1.11 (CYGWIN)
```

**Comment by tenthirtyam** [comment]
@nywilken - recommend closing based on prior solution provided - use of `oscdimg` via https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install (as referred to in the docs: https://www.packer.io/docs/builders/qemu#cd-configuration).


**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by nywilken** [comment]
Thanks for calling this out @tenthirtyam. Provided solution seems to be the way here. Thanks!

**Comment by alexeig** [comment]
> @mariotacke thanks for your reply. I just figured that out too, it works after adding `oscdimg` to the path. I had to restart my system for it to work.

In my case (Win11 Pro), didn't have to restart the system but did have to open a new command prompt / powershell session, which then had the updated path, and `packer build` then worked.

**Comment by Jabby007** [comment]
> mkisofs

where we have to install it? on vcenter nodes ?? Please help

**Comment by tenthirtyam** [comment]
> > mkisofs
> 
> where we have to install it? on vcenter nodes ?? Please help

On the system running the build with Packer.

**Comment by Jabby007** [comment]
> > > mkisofs
> > 
> > 
> > where we have to install it? on vcenter nodes ?? Please help
> 
> On the system running the build with Packer.

I'm building using jenkins pipeline, so I need to install on jenkens agent node ?

**Comment by tenthirtyam** [comment]
> I'm building using jenkins pipeline, so I need to install on jenkins agent node ?

Yes. Depending on the OS you will need one of the supported command line tools installed that can generate the ISO. creation. Packer will use one of the following tools based on the Packer SDK.

- `xorriso`
- `mkisofs`
- `hdiutil` (normally found in macOS)
- `oscdimg` (normally found in Windows as part of the Windows ADK)

**Comment by Jabby007** [comment]
I have installed xorriso and (mkisofs) genisoimage , but still getting same error. Below is my json file. Please help

            "boot_command": [
                "linux inst.ks=cdrom:/dev/sr0:/{{user `kickstart-file-name`}} ksdevice=eth0 net.ifnames=0 biosdevname=0<enter>"
            ],
            "boot_order": "cdrom",
            "boot_wait": "30s",
            "cluster": "{{user `vsphere-cluster`}}",
            "convert_to_template": true,
            "datacenter": "{{user `vsphere-datacenter`}}",
            "datastore": "{{user `vsphere-datastore`}}",
            "guest_os_type": "oracleLinux8_64Guest",
            "insecure_connection": "true",
            "cd_files": [
                "{{user `kickstart-file-name`}}"
            ],
            "iso_paths": [
                "{{user `iso_url`}}"
            ],

**Comment by patschi** [comment]
I encountered the same issue, but after installing Windows ADK and its "Deployment Tools" oscdimg was installed here:
`C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg\`

But as I was too lazy to restart CMD/my PC, I changed the PATH environment variable in runtime and packer was able to proceed:
```
PATH=%PATH%;C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg\
```

**Comment by kszabi777** [comment]
My packer is running on windows server 2016. I installed Windows ADK and added to the path and rebooted several times but still no luck, same error. 

If I type oscdimg in the prompt it finds it (so the path is working) but when I run the packer build I got the error. (could not find a supported CD ISO creation command)

Anyone has any idea please?

**Comment by jmo-anssi** [comment]
Hello,
In my case, starting from version 1.2.2 of this plugin, having oscdimg.exe in the current working directory when executing "packer build" throws the following error : "could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)".
But, if i don't have oscdimg.exe in the current working directory, and only have it available thanks to the PATH environment variable, it works.

**Comment by wiuzdev** [comment]
> Hello, In my case, starting from version 1.2.2 of this plugin, having oscdimg.exe in the current working directory when executing "packer build" throws the following error : "could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)". But, if i don't have oscdimg.exe in the current working directory, and only have it available thanks to the PATH environment variable, it works.

--> Thanks a lot for this. Indeed, if we do have oscdimg this issue happens. It is new.
