### ISSUE TITLE
Add support for native vSphere HTTP boot

### ISSUE THREAD

**Issue by jrsmile** [hashicorp/packer-plugin-vsphere#183]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

It would safe a lot of time and be a lot more robust to utilize the native http boot function of vsphere to boot an iso.
more here [click](https://williamlam.com/2021/03/simplified-nested-esxi-installation-in-esxi-7-0-update-2-using-http-boot-over-virtualefi.html)

#### Use Case(s)

as packer already serves the preseed via http it could do the same with the iso and just create an empty vm with the right http boot url configuration. a upload to a datastore is no longer necessary. furthermore http boot supports adding cmdline parameters for the kernel if booted via kernel image. (an extraction of the iso/mount would be necessary on the box that runs packer.)

**Comment by tenthirtyam** [comment]
Marking this item as **not planned**.
