### ISSUE TITLE
'configuration_parameters' not really usable

### ISSUE THREAD

**Issue by nneul** [hashicorp/packer-plugin-vsphere#190]
#### Overview of the Issue

I've been attempting to use the configuration_parameters option of vsphere-clone to provision a VM/template with vApp parameters enabled. Documentation indicates it's a direct interface to the vmConfigSpec - but it looks to me like it's actually a direct interface SOLELY to the 'extraConfig' element of vmConfigSpec. NOTE: I am NOT trying to _populate_ vApp property values, I'm trying to create a new vApp properties without having to do this with a post processor. 

Example calling syntax: 
```
  configuration_parameters = {
    vAppConfig = <<EOF
                <product>
                  <key>0</key>
                  <classId/>
                  <instanceId/>
                  <name/>
                  <vendor/>
                  <version/>
                  <fullVersion/>
                  <vendorUrl/>
                  <productUrl/>
                  <appUrl/>
                </product>
                <property>
                  <key>0</key>
                  <classId/>
                  <instanceId/>
                  <id>NET_NETMASK</id>
                  <category>OptionCategory</category>
                  <label>NET_NETMASK</label>
                  <type>string</type>
                  <typeReference/>
                  <userConfigurable>true</userConfigurable>
                  <defaultValue>255.255.255.0</defaultValue>
                  <value>255.255.255.0</value>
                  <description/>
                </property>
                <ipAssignment>
                  <ipAllocationPolicy>fixedPolicy</ipAllocationPolicy>
                  <supportedIpProtocol>IPv4</supportedIpProtocol>
                  <ipProtocol>IPv4</ipProtocol>
                </ipAssignment>
                <ovfEnvironmentTransport>com.vmware.guestInfo</ovfEnvironmentTransport>
                <installBootRequired>false</installBootRequired>
                <installBootStopDelay>0</installBootStopDelay>
EOF
  }
```

I was expecting this to result in a 'vAppConfig' key being added to the resulting XML of the VM - however checking the resulting VM manually, I see the content passed in as a xsd:string, bundled into an '<extraConfig>' element, and not even passed as-is - it's being html-encoded. 

Is this a usage problem or just lack of functionality?

```
<extraConfig><key>vAppConfig</key><value xsi:type="xsd:string">                &lt;product&gt;
                  &lt;key&gt;0&lt;/key&gt;
                  &lt;classId/&gt;
                  &lt;instanceId/&gt;
                  &lt;name/&gt;
                  &lt;vendor/&gt;
                  &lt;version/&gt;
                  &lt;fullVersion/&gt;
                  &lt;vendorUrl/&gt;
                  &lt;productUrl/&gt;
                  &lt;appUrl/&gt;
                &lt;/product&gt;
                &lt;property&gt;
                  &lt;key&gt;0&lt;/key&gt;
                  &lt;classId/&gt;
                  &lt;instanceId/&gt;
                  &lt;id&gt;NET_NETMASK&lt;/id&gt;
                  &lt;category&gt;OptionCategory&lt;/category&gt;
                  &lt;label&gt;NET_NETMASK&lt;/label&gt;
                  &lt;type&gt;string&lt;/type&gt;
                  &lt;typeReference/&gt;
                  &lt;userConfigurable&gt;true&lt;/userConfigurable&gt;
                  &lt;defaultValue&gt;255.255.255.0&lt;/defaultValue&gt;
                  &lt;value&gt;255.255.255.0&lt;/value&gt;
                  &lt;description/&gt;
                &lt;/property&gt;
                &lt;ipAssignment&gt;
                  &lt;ipAllocationPolicy&gt;fixedPolicy&lt;/ipAllocationPolicy&gt;
                  &lt;supportedIpProtocol&gt;IPv4&lt;/supportedIpProtocol&gt;
                  &lt;ipProtocol&gt;IPv4&lt;/ipProtocol&gt;
                &lt;/ipAssignment&gt;
                &lt;ovfEnvironmentTransport&gt;com.vmware.guestInfo&lt;/ovfEnvironmentTransport&gt;
                &lt;installBootRequired&gt;false&lt;/installBootRequired&gt;
                &lt;installBootStopDelay&gt;0&lt;/installBootStopDelay&gt;
</value></extraConfig>
```

What I'm wanting to see is:

```
<vAppConfig>
   <product>........</product>
   ...
</vAppConfig>
```

### Packer Version

1.8.0

### Plugin Version and Builders

- [X] `vsphere-clone`     (and potentially vsphere-iso as well)

### VMware vSphere Version

7.0.2

### Guest Operating System
     - Ubuntu 20.04 LTS x64

### Operating System and Environment Details

Running on ubuntu 20 x64.

### Log Fragments and `crash.log` Files

No errors, vm is provisioned, it just doesn't do anything useful since the vApp options are scrambled and not in the correct form for the  vmConfigSpec.

### Suggested actions

Assuming there isn't a way to get these passed in as described, update the docs with a usable example instead of just saying it's a direct passthrough. At least add change "passthrough to the vSphere API's ConfigSpec:" to "passthrough to the extraConfig field of vSphere API's ConfigSpec:"

### Alternative Workarounds?

Is there any way to run a post processor/provisioning step after VM shutdown, but _before_ conversion to template? Currently only real option I'm seeing would be to set convert_to_template to false and then run a pyvmomi or similar script to add the vApp config options along with the template conversion.

**Comment by robwesterby** [comment]
This problem has already been flagged in [issue #171](https://github.com/hashicorp/packer-plugin-vsphere/issues/171) (and before that in #45). Fixing it would likely close off a few other issues too.

That said it doesn't look easy to achieve without a breaking change, or new variable to replace `configuration_parameters`.

I'm intending to use a PowerShell wrapper script to apply the settings that Packer can't. As this needs to run after the Packer build completes, it means some of the built-in Packer vSphere functionality such as import to content library can't be used.

It doesn't look like this plugin gets much love these days, so use of some other scripting language is likely the only solution until someone with the appropriate knowledge & time pops up to make the code changes to this plugin.

Rob

**Comment by tenthirtyam** [comment]
@nywilken - looks like there are a couple duplicates to be labeled and closed.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by nywilken** [comment]
@nneul thanks for the detailed description. I'm going to close this issue so that we can track the request in #171. 

@tenthirtyam do you have any thoughts on how we can best proceed with supporting some of the requests with the current state of this Plugin? If not the team can work through the suggested actions to create a plan. Let me know.
