### ISSUE TITLE
Make network adapters optional when creating a new VM 

### ISSUE THREAD

**Issue by cibofo** [hashicorp/packer-plugin-vsphere#202]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently, when trying to create a VM without specifying a network adapter the build will fail.
The network_adapters option is not optional although it is not necessary for a complete build.

#### Use Case(s)

When you don't want to expose the VM to a network (security concerns).

**Comment by tenthirtyam** [comment]
Hi @cibofo 👋 ~

For this enhancement, how do you propose to patch or configure the machine image if it can not connect to a network? 

I suppose you _could_ use a PowerShell provisioner with the `Copy-VMFile` and `Invoke-VMScript` PowerCLI cmdlets, but that would be rather cumbersome.

Or rather, is the concern that you'd like to final machine image to remove all network interfaces so that those are added (or not) by your platform and / or Terraform at time of workload provisioning _vs_ machine image creation.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by cibofo** [comment]
Hi @tenthirtyam, thanks for the quick reply!

I'm referring to a use case where you only want the iso to vm automation, without further configuration on the packer side.

For example, creating a new vm from an iso (without exposing it to a network to prevent security threats) and later configuring it using a govc/govmomi workflow or hands on use with a vmrc session.

Or adding an iso to vm automation to an already existing govc/govmomi/pyvmomi/PowerCLI workflow.

Also, I don't think that the builder should prevent the creation of a vm with no network adapter if there is no need for it in the rest of the process.

**Comment by tenthirtyam** [comment]
This of course also assumes that the OS supports the ability to be configured via files (`cd_content` or `floppy_content`) vs an HTTP-based (`http_content`) bootstrap / kickstart.

The enhancement request is interesting, but in general, the same result may be possible by attaching the machine image to an port group that is simply not backed by any NICs or one that is configured with pvlans etc and no communicator.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by cibofo** [comment]
> This of course also assumes that the OS supports the ability to be configured via files (`cd_content` or `floppy_content`) vs an HTTP-based (`http_content`) bootstrap / kickstart.
> 
Yes, I had Windows10 in mind when opened the issue. 

>the same result may be possible by attaching the machine image to an port group that is simply not backed by any NICs
>
Wouldn't it mean I need to create a new port group for every vm? 
>or one that is configured with pvlans etc and no communicator.
>
Sounds good but I think that it would be simpler if I could just not specify any network adapters. 

> The enhancement request is interesting
>
I will work on a PR for it soon
