### ISSUE TITLE
No HCL examples in vSphere Template Post-Processor documentation

### ISSUE THREAD

**Issue by bloudraak** [hashicorp/packer-plugin-vsphere#205]
#### Overview of the Issue

There are no examples for HCL when reading the [vSphere Template Post-Processor](https://www.packer.io/plugins/post-processors/vsphere/vsphere-template) documentation

#### Reproduction Steps

Visit the [vSphere Template Post-Processor](https://www.packer.io/plugins/post-processors/vsphere/vsphere-template) documentation, and notice that examples are only for JSON.

**Comment by tenthirtyam** [comment]
**Recommended Labels**: 
- `documentation`
- `good-first-issue`

cc: @nywilken @sylviamoss

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
