### ISSUE TITLE
When using shared library, thin provisioned disk are converted to thick zeroed

### ISSUE THREAD

**Issue by ZeikoFr** [hashicorp/packer-plugin-vsphere#209]
#### Overview of the Issue

I'm creating Linux template with 2 disks in thin provisioning, the creation of the template with packer is correctly made, both disks are thin provisionned.

When the template is converted to OVF and uploaded to the library it seems that it convert the disk in thick lazy zeroed

#### Reproduction Steps

Create template with thin disk
Upload the template to a shared library
Create a vm with the uploaded template

### Packer Version
1.8.2

### Plugin Version and Builders

Please provide the plugin version.

     - 1.0.7

- [X] `vsphere-iso`
- [] `vsphere-clone`

### VMware vSphere Version

     - 7.0.3

### Guest Operating System

     - Debian 11 x64

### Simplified Packer Buildfile

Storage conf : 
```
storage {
      disk_size        = var.disk_size_sda
      disk_thin_provisioned = var.disk_thin_provisioned
  }
  storage {
      disk_size = var.disk_size_sdb
      disk_thin_provisioned = var.disk_thin_provisioned
  }
```

The variable `disk_thin_provisioned` value is `True`

This is the warning I've got when create a VM from template 

[https://ibb.co/Sw8ZZZT](https://ibb.co/Sw8ZZZT)

### Operating System and Environment Details

Please add any information you can provide about the environment.

     - Operating System:  Debian 11 x64

**Comment by tenthirtyam** [comment]
Hi @ZeikoFr,

What **warning** are you seeing presented? The screenshot is showing both the anticipated, but no ⚠️ specific warning.

What provisioning are you selecting for the target datastore, what is the target datastore type (e.g. VMFS, NFS, vSAN), and what are the results?

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by ZeikoFr** [comment]
Hi, sorry for the delay I was not able to answer sonner !

In the screenshot you can see on disk where the size is unknown (should be 1Gb) and thin provisioned, and second disk 15Gb thick provisioned, but both disk where created as thin provisioned.

All provisioning use vmware-iso (If I understood your question correctly)

When creating the VM that will be converted in OVF template, the datastore used is a local VMFS 6 datastore.

Then the template is uploaded to a local library (with is in the same vcenter server and then this library is shared to other vcenter) and the datastore used for the library is also VMFS 6.

Do I answered properly to your questions ? If you need more detail I will provide has much as I possibly can 

Regards

**Comment by tenthirtyam** [comment]
Are you using `vsphere-iso` or `vmware-iso`?

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
If you look in the content library, how big is the actual OVA?

In the image that you provided it's not showing two disks. It's showing what the _cumulative_ size would be of thin provisioned (unknown) or thick (15GB) for the OVA deployment and all its disks.

Once you deploy the OVA, it will provision based on selection and datastore type - default, thin, thick (LZ or EZ), or storage policy selection.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by ZeikoFr** [comment]
Sorry it's a typo I use vsphere-iso.

Regarding the OVF, according to what is shown in the Library, the size is 3.27Gb, it shows both drive with the correct size (one 14Gb and the other 1 GB) 

See here https://ibb.co/Cwj8cBp

So to be sure, whatever value I put in the template will be overwrite by datastore ty or storage policy ?

**Comment by tenthirtyam** [comment]
Based on what you've provided it looks accurate. If you wanted to check even further you could download the OVA locally and untar the .ova file. There you should see two .vmdk files that will confirm the sizing. If thick, they will be the size of the defined disks, if thin they will be smaller based on only what was installed during the build operation.

When you deploy the OVA to your target you can select the destination datastore and select the desired provisioning based on the need - datastore default, thin, thick lz/ez, or even based on a storage policy. Keep in mind that some datastore types are thin by default (eg vSAN and NFS).

Additionally, I suggest **not** using the image service that you've chosen when linking a screenshot as it has inappropriate ads that may conflict with the project's code of conduct. You can simply copy and paste images directly into the GitHub issue.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by ZeikoFr** [comment]
Thanks for your explanation and your time !

Has for the images hosting sorry I didn't know it had ads, I have a network-wide adblock + ublock origin and a JS Blocker.

**Comment by tenthirtyam** [comment]
Happy to help!

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
