### ISSUE TITLE
Plugin should not require global read permissions

### ISSUE THREAD

**Issue by braunsonm** [hashicorp/packer-plugin-vsphere#210]
#### Description
As it stands right now. The packer vsphere plugin states to give the account access to global System.Read on the whole cluster. In particular we've noticed this being a requirement when searching for the distributed virtual switch, it seems to start from the cluster and work its way down to find the port groups. 

Ideally, we would like the requirement for global read to be removed. This is a sticking point for multi-tenancy in our organization. I was wondering if there was not any applicable vSphere APIs that can be used instead to find these objects without needing to traverse the entire cluster.

#### Use Case(s)
- Enhanced security model
- Easier multi-tenancy

#### Potential configuration

Instead of global read permissions, read can be granted on the port groups necessary and the plugin can search all port groups which it can see. Instead of looking for a DVS, then listing its port groups.

If there is any reason this cannot be done in this way, please let me know.

**Comment by tenthirtyam** [comment]
Note: the Packer plugin plug-in [uses](https://github.com/hashicorp/packer-plugin-vsphere/blob/main/builder/vsphere/driver/network.go) [`finder.network`](https://github.com/vmware/govmomi/blob/f7bbf3db22758f787c5825bd75fcfd7c81cd5fa3/find/finder.go#L793-L821) from `vmware/govmomi`. Would need to check to see if there is an upstream requirement from `govmomi`.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Do you see the same issue if you use the inventory path for the object name?

**Comment by tenthirtyam** [comment]
No reply from OP. No upvotes or additional community comments.
