### ISSUE TITLE
"Invalid configuration for device '0'" when >1 network uses the same name in the vSphere inventory

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vsphere#213]
_This issue was originally opened by @eperts in https://github.com/hashicorp/packer/issues/11963 and has been migrated to this repository. The original issue description is below._

---

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I'm trying to run a Packer build to get a windows 10 template for Horizon VDI. My build runs fine in our lab environment, but in our production environment, it cannot find the correct network. There are several networks with the same name so I am specifying the entire path down to the correct network. Using the same structure that worked without issues in our lab environment, it does not work in the production environment. 

The error that comes back is: Invalid configuration for device '0'. 

I cannot use a different network for the production vCenter. 

When I cut it down to just the network name, it comes back with an error: path '<network name>' resolves to multiples provide a host to match or full network path. 

The path I'm using is, essentially: /<datacenter>/network/<switch>/<name of network>

Again, this works in our test vCenter, but not production. If anyone has run into this issue before, I'd appreciate any advice.

**Comment by tenthirtyam** [comment]
Today, the plugin does not support the use of data sources (_see plugin enhancement request_ GH-196). With this limitation of filtering networks and filtering those with the same name within the vSphere inventory (one or more linked instances) in mind and assuming that you are using services accounts, one workaround may be to limit the scope for the service account to only those networks that are applicable for the build processes. If you're using the content library, you'll need Global Permissions, but at the network level you can reduce the visibility of the networks readable by the service account depending on how you've organized the inventory, for example, with network folders.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
For general questions, we recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for greater visibility.  The GitHub issue tracker is only watched by a small group of maintainers and collaborators and is typically reserved for bug reports and enhancement request. You will typically have more success finding assistance on the forum.

If you find the forum to be more helpful or if you've found the answer to your question elsewhere, please comment and close the issue. If there is no further activity on this question within the next 30 days it will be closed.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
