### ISSUE TITLE
`vsphere-iso`:  Unable to enter virtual machine into boot options at power on

### ISSUE THREAD

**Issue by KrzesloSzatan** [hashicorp/packer-plugin-vsphere#228]
Hello, I am trying to run packer for a vsphere vm using vsphere-iso and i do have one small but very crucial problem.... And its the same both on EFI or normal BIOS. I am able to get into boot options once for like 15 times.... The issue is that packer gets (or vsphere sends) information about VM is turned ON too late. When I go to the web console (instantly when it shows up and i compared it with console output from packer which is the same exact moment) its almost always past the moment where i can interrupt boot select and add boot_command. I always end up with packer trying to type in boot_command while native installer is already on. I have setup boot_wait parameter to -1s-10s and its like always vm starts before vsphere show it has actually started.

I have tried to add

```
configuration_parameters {
"bootOptions.bootDelay": 10000
}
```

but nothing has changed and it doesn't work as when i add this manually via GUI.

Sometimes it works fine, VM is powered ON and it shows the boot menu and packer interrupts it and everything works, but the whole point is so it won't do it once a year but every time i want it to run :)

Do you have any ideas why it works (or not ?) like that and/or how to handle this issue ?

**Comment by tenthirtyam** [comment]
Is there a particular guest operating system and vSphere version?

**Comment by tenthirtyam** [comment]
Awaiting a reply for [prior inquiry](https://github.com/hashicorp/packer-plugin-vsphere/issues/228#issuecomment-1288121253).

For general questions, we recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for greater visibility.  The GitHub issue tracker is only watched by a small group of maintainers and collaborators and is typically reserved for bug reports and enhancement requests. You will typically have more success finding assistance on the forum.

If you find the forum to be more helpful or if you've found the answer to your question elsewhere, please comment and close the issue. If there is no further activity on this question within the next 30 days it will be closed.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Marking this issue as closed. If this issue is reproducible with the latest version of the plugin', please create a new issue linking back to this one for added context. 

Thank you!

**Comment by tenthirtyam** [comment]
This is addressed in pull request https://github.com/vmware/packer-plugin-vsphere/pull/773 tracked under #507.
