### ISSUE TITLE
Packer waits at IP until timeout

### ISSUE THREAD

**Issue by paulgiordano** [hashicorp/packer-plugin-vsphere#243]
#### Overview of the Issue

Running a packer build using vsphere-clone waits until timeout at "Waiting for IP..." because the NIC is not connected after the clone.

#### Reproduction Steps

Created a template for Ubuntu 22.04.1 from the ISO, set it up for NIC connected on startup. (Created from implemented VM)

### Packer Version

1.8.5

### Plugin Version and Builders

1.1.1

Please select the builder.

- [] `vsphere-iso`
- [X] `vsphere-clone`

### VMware vSphere Version

7.0.1

### Guest Operating System

Ubuntu 22.04.1

### Simplified Packer Buildfile

https://gist.github.com/paulgiordano/40f4546a64f551f7f60b4ee8dc6b4de2

### Operating System and Environment Details

Running on a Linux VM, Ubuntu 22.04.1 standard environment.

### Log Fragments and `crash.log` Files

See above gist

**Comment by tenthirtyam** [comment]
Is this still an issue!

**Comment by paulgiordano** [comment]
I basically gave up since I didn't hear anything, worked out another solution. It's a shame really, I liked the environment and all.
