### ISSUE TITLE
`vsphere-clone`: Error: "Customization of the guest operating system is not supported due to the given reason"

### ISSUE THREAD

**Issue by davidthong** [hashicorp/packer-plugin-vsphere#254]
Having an issue with using vsphere clone builder using windows. Getting this error.

Customization of the guest operating system is not supported due to the given reason: \

But there is no reason according the above error statement.

Here's my builder hcl ( it's a jijna template )

```
source "vsphere-clone" "goldenimage" {
  communicator        = "winrm"
  insecure_connection = "true"
  password            = "{{ vcenter_password }}"
  template            = "W2K22_Template"
  username            = "{{ packer_vmware_user }}"
  vcenter_server      = "{{ vcenter_hostname }}"
  datacenter          = "{{ packer_vmware_data_center }}"
  cluster             = "{{ packer_vmware_cluster }}"
  host                = "{{ packer_vmware_host }}"
  datastore           = "{{ packer_vmware_datastore }}"
  vm_name             = "golden_image_{{ survey_os_type }}_{{ ansible_date_time.iso8601_basic_short }}"
  folder              = "GoldenImages"
  convert_to_template = "true"
  winrm_username      = "Administrator"
  winrm_password      = "{{ vmware_windows_template_password }}"
  winrm_port          = "5986"
  network              = "Production-VLAN49"
  
  customize { 

    windows_options {
      computer_name = "packergoldenimage"
      admin_password = "{{ vmware_windows_template_password }}"
      run_once_command_list = ["echo hello"]
    

     }
 
     network_interface {
          ipv4_address = "10.10.229.100"
          ipv4_netmask = "20"
         dns_server_list = ["10.232.121.10", "10.232.121.117", "10.76.106.6"]
        }

      ipv4_gateway = "10.10.224.1"

  }
}
```

**Comment by davidthong** [comment]
Here are more logs..  
[packer-vsphereclone.log](https://github.com/hashicorp/packer-plugin-vsphere/files/10736655/packer-vsphereclone.log)

**Comment by nywilken** [comment]
This error appears to be an upstream error being returned by vSphere when trying to customize the VM. @tenthirtyam do you have any insight on when this particular error may occur Of if there is any specific requirements for what looks to be be a Windows 2022 vm. 

@davidthong I'm not to familiar with the customization process but does the clone have all of the required vmware tools installed to allow for customization? 

I've seen other threads around the this related to the vmware tools not being installed or needing repair. Hoping @tenthirtyam can shed some light.

**Comment by 3X0mre** [comment]
It could be something else, but windows computer names should be 15 characters max according to [this](https://learn.microsoft.com/en-US/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou#netbios-computer-names). @davidthong maybe try with a shorter name?

**Comment by tenthirtyam** [comment]
> It could be something else, but windows computer names should be 15 characters max according to [this](https://learn.microsoft.com/en-US/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou#netbios-computer-names).

17 characters used.
