### ISSUE TITLE
Receiving ID not implemented for builder when using build.ID

### ISSUE THREAD

**Issue by jocon128** [hashicorp/packer-plugin-vsphere#256]
#### Overview of the Issue

When trying to pass through build.ID to shell-local post processor the evaluate string in the post processor is ERR_ID_NOT_IMPLEMENTED_BY_BUILDER I am using vsphere-iso.

### Packer version

`1.8.4`

### Simplified Packer Template
```hcl
  post-processor "shell-local" {
    environment_vars = [
      "VCENTER_USER=${var.vsphere_username}",
      "VCENTER_PASSWORD=${var.vsphere_password}",
      "VCENTER_SERVER=${var.vsphere_endpoint}",
      "TEMPLATE_NAME=${build.ID}",
      "TEMPLATE_UUID=${local.build_uuid}",
    ]
    env_var_format  = "$env:%s=\"%s\"; "
    execute_command = ["${var.common_post_processor_cli}.exe", "{{.Vars}} {{.Script}}"]
    script          = "scripts/windows/cleanup.ps1"
  }
```

### Post processor script
```ps1
param(
    [string]
    $TemplateName = $env:TEMPLATE_NAME
)
Write-Host $TemplateName
```
### Operating system and Environment details

Windows Server 2019 (17763.3046) x64

### Log Fragments and crash.log files

```
==> vsphere-iso.windows-server-standard-dexp (shell-local): Running local shell script: scripts/windows/cleanup.ps1
    vsphere-iso.windows-server-standard-dexp (shell-local): ERR_ID_NOT_IMPLEMENTED_BY_BUILDER
```

**Comment by tenthirtyam** [comment]
No reply by OP and no upvotes.

**Comment by JesseHermes** [comment]
According to the Packer Documentation for Contextual Variables, build.ID should be the name of the VM
https://developer.hashicorp.com/packer/docs/templates/hcl_templates/contextual-variables
Under the Heading Build Variables -> ID
ID: Represents the VM being provisioned. For example, in Amazon it is the instance ID; in DigitalOcean, it is the Droplet ID; in VMware, it is the VM name.
