### ISSUE TITLE
Precise "hardware_version" behavior in vSphere port-processor

### ISSUE THREAD

**Issue by LuckyDams** [hashicorp/packer-plugin-vsphere#260]
Hi,
From documentation, `hardware_version` in vSphere port-processor is described as:
> The virtual hardware version that the VM should be deployed with. Use when deploying to vSphere / ESXi host whose version is different than the the one used to create the artifact.  

ref: [hardware_version](https://developer.hashicorp.com/packer/plugins/post-processors/vsphere/vsphere#hardware_version)

From my understanding, this parameter uses ovftool option `--maxVirtualHardwareVersion` underneath. Which is described as:
> The maximal virtual hardware version to generate.

https://github.com/hashicorp/packer-plugin-vsphere/blob/27b65677962687341d720fa926d5223d8ef2dbda/post-processor/vsphere/post-processor.go#L266

I am not english native but I believe the documentation would lead to wrong assumption of the behavior of this option.

From my tests, setting `hardware_version` to a higher version than the one defined in a source OVA is not deploying a VM in the requested version (but preserve original one).

Could you please precise the expected behavior of this option or review documentation ?

**Comment by tenthirtyam** [comment]
The `hardware_version` option in the vSphere post-processor is indeed used to set the `--maxVirtualHardwareVersion` option in the ovftool. This option specifies the maximum virtual hardware version to generate for the VM.

However, the ovftool's `--maxVirtualHardwareVersion` option doesn't upgrade the virtual hardware version of the source VM. Instead, it limits the virtual hardware version of the deployed VM to the specified version. If the source VM's hardware version is higher than the specified version, the deployed VM's hardware version will be downgraded to the specified version. If the source VM's hardware version is lower than or equal to the specified version, the deployed VM's hardware version will be the same as the source VM's.

So, if you set `hardware_version` to a higher version than the source OVA's hardware version, the deployed VM's hardware version will still be the same as the source OVA's. The `hardware_version` option doesn't upgrade the hardware version.

The documentation could indeed be clearer about this. It should mention that the `hardware_version` option sets the maximum virtual hardware version and doesn't upgrade the hardware version.

I'll get this added.

**Comment by LuckyDams** [comment]
Thanks for the clarification.
