### ISSUE TITLE
`vsphere-iso`: parallel jobs with same iso fails first time

### ISSUE THREAD

**Issue by goodlegolas** [hashicorp/packer-plugin-vsphere#266]
I'm trying to install multiple servers with the same ISO file using iso_url of a local file. When the file is not present in the datastore one job uploads the file and the other jobs thinks that it is present in the datastore and continues, and thus fails to boot. Running the same job with the ISO already present in the datastore everything works perfect. This seems related to #55.

**Comment by tenthirtyam** [comment]
Sounds like a race condition / corner case. One idea is to modify the plugin to hold all builds until the ISO upload is completed.
