### ISSUE TITLE
Add support to output file permission and ownership

### ISSUE THREAD

**Issue by MrKeiKun** [hashicorp/packer-plugin-vsphere#280]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Allow `vsphere-iso`/`vsphere-clone` to customize the file permission and ownership of the output file.

**Comment by tenthirtyam** [comment]
What's the usecase - for exported OVF to the Packer host?

**Comment by MrKeiKun** [comment]
> What's the usecase - for exported OVF to the Packer host?

This is great whenever image is exported to a NAS and be used in a workflow of building image and running the image post-provisioning like tenable scan or such.

**Comment by tenthirtyam** [comment]
Today a portion of this can be done using `output_directory` and `directory_permission`.

> _"The permissions to apply to the "output_directory", and to any parent directories that get created for output_directory.  By default this is "0750". You should express the permission as quoted string with a leading zero such as "0755" in JSON file, because JSON does not support octal value. In Unix-like OS, the actual permission may differ from this value because of umask."_

**Comment by tenthirtyam** [comment]
Taking a look at this there have not been any upvotes for such an enhancement; however, I did notice that there should be some error handling for the export with permissions should ensure that the os is not Windows. I'll address this one.
