### ISSUE TITLE
`vsphere-iso`: Error closing rest client session

### ISSUE THREAD

**Issue by tenthirtyam** [hashicorp/packer-plugin-vsphere#286]
#### Overview of the Issue

Whilst running a `vsphere-iso` build using `v1.2.0` of the plugin, an error is raised during the session `Cleanup()`.

```console
==> vsphere-iso.linux-photon: Built on: 2023-06-15 23:28 UTC
==> vsphere-iso.linux-photon: Built by: HashiCorp Packer 1.9.1'...
==> vsphere-iso.linux-photon: Destroying VM...
    vsphere-iso.linux-photon: Closing sessions ....
    vsphere-iso.linux-photon: Error closing rest client session: DELETE https://sfo-m01-vc01.sfo.rainpole.io/rest/com/vmware/cis/session: 401 Unauthorized
==> vsphere-iso.linux-photon: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-photon' finished after 3 minutes 38 seconds.

==> Wait completed after 3 minutes 38 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.linux-photon: linux-photon-5.0
--> vsphere-iso.linux-photon: linux-photon-5.0-
Done.
```

#### Reference

https://github.com/hashicorp/packer-plugin-vsphere/pull/272 (cc: @ruospalo)
https://github.com/hashicorp/packer-plugin-vsphere/issues/217

#### Reproduction Steps

Run a build with Packer and the plugin using the versions listed below.

### Packer Version

`v1.9.1`

### Plugin Version and Builders

`v1.2.0`
`vsphere-iso`

### VMware vSphere Version

8.0 Update 1 (`v8.0.1`)

### Guest Operating System

VMware Photon OS 5.0 (or any other)

### Simplified Packer Buildfile

See `main` in [Packer Examples for VMware vSphere.](https://github.com/vmware-samples/packer-examples-for-vsphere/)

### Operating System and Environment Details

Ubuntu 22.04 LTS x64

### Log Fragments and `crash.log` Files

```console
==> vsphere-iso.linux-photon: Built on: 2023-06-15 23:28 UTC
==> vsphere-iso.linux-photon: Built by: HashiCorp Packer 1.9.1'...
==> vsphere-iso.linux-photon: Destroying VM...
    vsphere-iso.linux-photon: Closing sessions ....
    vsphere-iso.linux-photon: Error closing rest client session: DELETE https://sfo-m01-vc01.sfo.rainpole.io/rest/com/vmware/cis/session: 401 Unauthorized
==> vsphere-iso.linux-photon: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-photon' finished after 3 minutes 38 seconds.

==> Wait completed after 3 minutes 38 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.linux-photon: linux-photon-5.0
--> vsphere-iso.linux-photon: linux-photon-5.0-
Done.
```

**Comment by dvm191** [comment]
also running into this issue!

**Comment by tenthirtyam** [comment]
I've asked @ruospalo to take a look into it as it appears to be related to an enhancement @ruospalo implemented for 1.2.0.

Please use the reactions 👍 to upvote.

**Comment by dvm191** [comment]
is there a workaround?

**Comment by ruospalo** [comment]
The message says that it was unable to close one of the opened sessions,
but should package correctly the image.

In previous versions, it did not close any sessions, so it should have the
same behaviours.

After 1 hour, the sessions will be closed automatically by vSphere.

**Comment by ruospalo** [comment]
After reviewing it, the problem is that there is 2 calls to clean the session. The first one already cleans the session, but the second gives a 401 unauthorised and show an error message, but package correctly the image.
 
The session is cleaned correctly and the second call is innocuous and unnecessary.

**Comment by ruospalo** [comment]
I believe that the best is to log a WARN message instead of showing in the UI. I'll create a PR for that.
