### ISSUE TITLE
Out-of-date source repo in documenation?

### ISSUE THREAD

**Issue by lindhe** [hashicorp/packer-plugin-vsphere#288]
Is this link out of date? AFAICT, the repo exists here on <https://github.com/hashicorp/packer-plugin-vsphere> not <https://github.com/hashicorp/vsphere>.

https://github.com/hashicorp/packer-plugin-vsphere/blob/5dfa6e5da2bdf1f7427878df0efa49f3cf115fea/docs/builders/index.mdx#L41

**Comment by tenthirtyam** [comment]
Each of the HashiCorp Packer plugins follow this source format.

cc @nywilken

**Comment by lindhe** [comment]
Curiously, I found this comment [in the code](https://github.com/hashicorp/packer/blob/9c85fc274af579aee846b21cdbc0b89f8eaefb0f/hcl2template/addrs/plugin.go#L163-L171):

> 	// Due to how plugin executables are named and plugin git repositories
>	// are conventionally named, it's a reasonable and
>	// apparently-somewhat-common user error to incorrectly use the
>	// "packer-plugin-" prefix in a plugin source address. There is
>	// no good reason for a plugin to have the prefix "packer-" anyway,
>	// so we've made that invalid from the start both so we can give feedback
>	// to plugin developers about the packer- prefix being redundant
>	// and give specialized feedback to folks who **incorrectly use the full**
>	// **packer-plugin- prefix** to help them self-correct.

Does this mean that this repo is technically incorrectly named according to your own best practices?

**Comment by tenthirtyam** [comment]
This concern would best be addressed in hashicorp/packer as this is the naming convention for most all registered plugin projects, not just this plugin.

Ref: https://github.com/hashicorp/packer/blob/main/website/data/plugins-manifest.json
