### ISSUE TITLE
Allow for custom CA with `insecure_connection=false`

### ISSUE THREAD

**Issue by lindhe** [hashicorp/packer-plugin-vsphere#291]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

I would like to have a field in the source block where one can define the path to a certificate file for a custom CA to be trusted when connecting to the vCenter Server instance.

#### Use Case(s)

In our current environment, the vCenter Server we connect to has a TLS certificate from a private CA. Today, we must set `insecure_connection=true` to run Packer towards the server. We would like to be able to provide our own CA certificate for Packer to trust, so we can verify that the connection is secure despite not using a publicly trusted CA.

#### Potential configuration

```hcl
packer {
  required_plugins {
    vsphere = {
      version = ">= v1.3.0"
      source  = "github.com/hashicorp/vsphere"
    }
  }
}

source "vsphere-iso" "linux-ubuntu" {

  vcenter_server      = var.vsphere_endpoint
  username            = var.vsphere_username
  password            = var.vsphere_password

  insecure_connection = false
  ca_certificate      = "./ca.crt"

  […]
}

[…]
```

**Comment by goldstar611** [comment]
I would like to add that I have updated `/usr/lib/vmware-ovftool/certs/cacert.pem` in attempt to accomplish this but with no success, the connection still appears untrusted.

**Comment by tenthirtyam** [comment]
> I would like to add that I have updated `/usr/lib/vmware-ovftool/certs/cacert.pem` in attempt to accomplish this but with no success, the connection still appears untrusted.

Yes, this would not work since ovftool is not used by the `vsphere-iso` builder in this context - relevant only for the post-processor. 😃

**Comment by tenthirtyam** [comment]
@lindhe - can your packer host (static or ephemeral) not import and trust the CA thus allowing the plugin to function with `insecure = false`?
