### ISSUE TITLE
Support for Disk Storage Location and Storage Policy

### ISSUE THREAD

**Issue by ArchaicLord** [hashicorp/packer-plugin-vsphere#294]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description
I would like to provision VMs with multiple disks from different storage locations within ESX and assign the correct storage policy.

I.E The main OS disk would be set to an SSD and an additional Data disk would be set to a standard HDD.

#### Use Case(s)
Nearly all of our systems are built with an OS drive on SSD and data disks on HDD.

#### Potential configuration

```
Storage {
  "disk_size": 20000,
  "disk_thin_provisioned": true,
  "stroage_location": "my_SSD_data_store",
  "vm_storage_policy": "my_storage_policy"

}
Storage {
  "disk_size": 20000,
  "disk_thin_provisioned": true,
  "stroage_location": "my_HDD_data_store",
  "vm_storage_policy": "my_storage_policy"
}
```

**Comment by webcompas** [comment]
There is already a similar issue (#18).

**Comment by tenthirtyam** [comment]
Duplicate #18
