### ISSUE TITLE
vsphere-iso: running scripts against terraform created VM from vsphere-iso exported as OVF

### ISSUE THREAD

**Issue by adeturner** [hashicorp/packer-plugin-vsphere#305]
#### Overview of the Issue

If I create a vsphere-iso image and export it as a OVF, and then try to instantiate it via vsphere_virtual_machine there is currently no easy way that I can run scripts against the VM.

There are three blockers from a terraform perspective

- vsphere_virtual_machine.vApp properties cannot be used as it is still a vsphere-iso enhancement #44

- vsphere_virtual_machine.linux_options.script_text fails due to [1915 Add support for Option to enable vmware-toolbox-cmd config set deployPkg enable-custom-scripts true](https://github.com/hashicorp/terraform-provider-vsphere/issues/1915)

- vsphere_virtual_machine.extra_config fails due to [1124 guestinfo.userdata in extra_config not passed to resource configuration when using OVF](https://github.com/hashicorp/terraform-provider-vsphere/issues/1124) and the [docs](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#extra_config) stating "Do not use extra_config when working with a template imported from OVF/OVA as your settings may be ignored. Use the vapp block properties section as described in [Using vApp Properties for OVF/OVA Configuration](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#using-vapp-properties-for-ovf-ova-configuration)."

I'm raising a bug because the enhancement already exists in this repo and I'd like to draw attention to it, and to see if there are any good examples of a work around.

**Comment by tenthirtyam** [comment]
Duplicate #44

**Comment by tenthirtyam** [comment]
No need for the additional issue. 

Plan to review this one soon with @nywilken.
