### ISSUE TITLE
Add support for reusing a virtual machine

### ISSUE THREAD

**Issue by Hi-Angel** [hashicorp/packer-plugin-vsphere#334]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently there's no functional to install an ISO to an existing VM. Rephrasing in packer terms: there's no way to build a machine image in vsphere by re-using an existing VM.

As a matter of fact, [judging by the lack of answers here](https://groups.google.com/g/packer-tool/c/BIEmO7hC1n0), it doesn't seem to be possible for any hypervisor, not just vsphere.

#### Use Case(s)

* Limiting the existing VMs to certain number of pre-created ones. `packer` is for automated VMs creation, and if there's a bug in the logic that calls packer, there may be an explosion of creating new VMs.
* ***(our usecase)*** working around missing functionality in the plugin. For example, there's currently no way to create a pair of VMs connected as an active/active or active/passive cluster *(that is having VMs with simultaneous access to the same "disk" or rather "disk file")*. Such functional is also difficult to implement because it does not work well in vSphere to start with. E.g. if you try to destroy such VM that shares a disk you'll get a vague `concurrent access` error.

**Comment by Hi-Angel** [comment]
I want to point out that I'm currently working on it. I'm new to both Packer and Go language, but hopefully if resources permit I will have it implemented.

Any advises are welcome.

**Comment by Hi-Angel** [comment]
Is there a way to avoid the plugin being killed while being paused under `gdb`?

**Comment by tenthirtyam** [comment]
I've added the `stage/thinking` label to this one. This seems to be a rather interesting use case but likely not quite common. Would be good to get community reactions 👍 👎 👀 or thoughts before implementing such feature.
