### ISSUE TITLE
Uploaded cdrom iso is not cleaned up from remote packer_cache directory

### ISSUE THREAD

**Issue by mike406** [hashicorp/packer-plugin-vsphere#356]
#### Overview of the Issue

Over time the remote `packer_cache` directory in the specified vSphere datastore accumulates `packerXXXXXXXXXX.iso` CD images. These are not being cleaned up automatically after a build succeeds.

#### Reproduction Steps
Add any `cd_files` or `cd_content` to packer template and build the VM. After build is complete, the .iso image remains in vSphere datastore `packer_cache` directory

### Packer Version

1.10.0

### Plugin Version and Builders

Please provide the plugin version.

packer-plugin-vsphere_v1.2.3_x5.0_windows_amd64

Please select the builder.

- [x] `vsphere-iso`

### VMware vSphere Version

Please provide the VMware vSphere version.

8.0

### Guest Operating System

Windows 10 x64

**Comment by tenthirtyam** [comment]
Duplicate of #14.
