### ISSUE TITLE
1.2.5 No longer builds Windows 2019 & 2022 

### ISSUE THREAD

**Issue by StephenSo** [hashicorp/packer-plugin-vsphere#386]
#### Overview of the Issue

Packer build for a given Windows server build no longer works, with the OS install ISO and VMWare tools ISOs getting swapped. 
Version 1.2.4 and older:
D: = Windows Install media ISO
E: = VMware Tools ISO

Version 1.2.5:
D: = VMware Tools ISO
E: = Windows Install media ISO

#### Reproduction Steps

Works as per previous version: KO Packer build where 
```
packer {
  required_plugins {
    ansible = {
      version = ">= 1.1.1"
      source  = "github.com/hashicorp/ansible"
    }
    vsphere = { # added due to https://www.hashicorp.com/blog/announcing-the-removal-of-bundled-plugins-in-hashicorp-packer
      version = "= 1.2.4"
      source  = "github.com/hashicorp/vsphere"
    }
  }
}
```
Change to 1.2.5 - Build will timeout waiting for VMTools to install
```
packer {
  required_plugins {
    ansible = {
      version = ">= 1.1.1"
      source  = "github.com/hashicorp/ansible"
    }
    vsphere = { # added due to https://www.hashicorp.com/blog/announcing-the-removal-of-bundled-plugins-in-hashicorp-packer
      version >= "= 1.2.5"
      source  = "github.com/hashicorp/vsphere"
    }
  }
}
```

### Packer Version

1.8.3

### Plugin Version and Builders

Please provide the plugin version.

1.2.5

Please select the builder.

- [] `vsphere-iso`

### VMware vSphere Version

Please provide the VMware vSphere version.

vCenter Server 7.0 Update 3o
VMware ESXi 7.0 Update 3g

### Guest Operating System

Windows 2022 & 2019

### Simplified Packer Buildfile
```
source "vsphere-iso" "windows2022" {
  // https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/builds/windows/server/2016/windows-server.pkr.hcl
  // vSphere & VM Configuration
  username            = var.vcenter_username
  password            = var.vcenter_password
  vcenter_server      = var.vcenter_server
  insecure_connection = true
  cluster             = var.vcenter_cluster
  folder              = var.vcenter_folder
  datastore           = var.vcenter_datastore
  vm_name             = "${var.windows2022_vm_name}-${var.buildtime}"
  // VM Version
  vm_version          = var.tac_vmxVersion
  // 
  firmware            = var.windows2022_vm_firmware
  // 
  vTPM                = false
  CPUs                = var.windows2022_vm_cpu_sockets
  cpu_cores           = var.windows2022_vm_cpu_cores
  // CPU_hot_plug         = var.vm_cpu_hot_add
  // RAM_hot_plug         = var.vm_mem_hot_add
  RAM                 = var.windows2022_vm_memory_sizeMB
  RAM_reserve_all     = true
  disk_controller_type= ["pvscsi"]
  storage {
      disk_size       = var.windows2022_vm_disk_sizeMB
      disk_controller_index = 0      
      disk_thin_provisioned = true
  }
  network_adapters {
      network         = var.vcenter_network
      network_card    = "vmxnet3"
  }
  cdrom_type          = var.windows2022_vm_cdrom_type
  remove_cdrom        = true
  reattach_cdroms     = 1

  // vSphere template settings
  convert_to_template = true
  export {
    force = true
    output_directory = var.ovfFile_location
  }
  create_snapshot     = false
  // OS Configuration
  guest_os_type       = "${var.windows2022_vm_guest_os_type}"
  notes               = "Default User: ${var.winrm_username}\nBuilt by Packer @ {{isotime \"2006-01-02 03:04\"}}."

  // Removable Media Settings
  iso_url             = "${var.windows_artifcatory}${var.windows2022_iso}"
  iso_target_path     = "${var.PACKER_CACHE_DIR}/${var.windows2022_iso}"
  iso_checksum        = var.windows2022_checksum
  iso_paths    = ["[] /vmimages/tools-isoimages/${var.windows2022_os_family}.iso"]
  floppy_files = [
    "${var.os_config_root}/${var.windows2022_os_family}/${var.windows2022_scripts_folder}/"
  ]
  floppy_content = {
    "autounattend.xml" = templatefile("${var.os_config_root}/${var.windows2022_os_family}/${var.windows2022_scripts_folder}/${var.windows2022_vm_firmware}_autounattend.pkrtpl.hcl", {
      vm_guest_os_language = var.windows2022_vm_guest_os_language
      vm_guest_os_keyboard = var.windows2022_vm_guest_os_keyboard
      vm_guest_os_timezone = var.windows2022_vm_guest_os_timezone
    })
  }

  // Boot and Provisioning Settings
  // http_port_min    = var.common_http_port_min
  // http_port_max    = var.common_http_port_max
  boot_order       = var.windows2022_vm_boot_order
  boot_wait        = var.windows2022_vm_boot_wait
  boot_command     = var.windows2022_vm_boot_command
  // ip_wait_timeout  = var.common_ip_wait_timeout
  shutdown_command = var.windows2022_vm_shutdown_command
  disable_shutdown = true  # Because "win_cloudbaseinit.ps1" shuts the VM down for us
  // shutdown_timeout = var.common_shutdown_timeout

  // Communicator Settings and Credentials
  communicator        = "winrm"
  winrm_username      = var.winrm_username
  winrm_password      = var.winrm_password
  // winrm_port          = var.communicator_port
  // winrm_timeout       = var.communicator_timeout
  winrm_insecure      = true
  // winrm_use_ssl       = true

}
```

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by Hi-Angel** [comment]
> @Hi-Angel - could you please take a look to see if the refactoring in #355 might have affected this behavior.

From what I read at the top post, it seems like the order has changed? It indeed sounds like the expected outcome [of this commit](https://github.com/hashicorp/packer-plugin-vsphere/pull/355/commits/27d5a49dcdb8ac67ec1183aa2887852034531069) *(referring at PR because all commits were squashed upon merge, so they're only distinguishable there)*.

I'm not quite clear though, why is that a problem. Unless I'm missing something, the plugin does not document any guarantees about the order in which ISO files will be mounted. The proper course of action on the user's side would be to fetch info after the VM got created about which disk has which ISO, and then work from there. Am I wrong here?

**Comment by StephenSo** [comment]
> > @Hi-Angel - could you please take a look to see if the refactoring in #355 might have affected this behavior.
> 
> From what I read at the top post, it seems like the order has changed? It indeed sounds like the expected outcome [of this commit](https://github.com/hashicorp/packer-plugin-vsphere/pull/355/commits/27d5a49dcdb8ac67ec1183aa2887852034531069) _(referring at PR because all commits were squashed upon merge, so they're only distinguishable there)_.
> 
> I'm not quite clear though, why is that a problem. Unless I'm missing something, the plugin does not document any guarantees about the order in which ISO files will be mounted. The proper course of action on the user's side would be to fetch info after the VM got created about which disk has which ISO, and then work from there. Am I wrong here?

In [Packer docs](https://developer.hashicorp.com/packer/integrations/hashicorp/vsphere/latest/components/builder/vsphere-iso#cdrom-configuration) 
"_If the "iso_url" is defined in addition to the "iso_paths", the "iso_url" is added to the VM first. This keeps the "iso_url" first in the boot order by default allowing the boot iso being defined by the iso_url and the vmware tools iso added from the datastore._"

Also, there are references to VMware VM hardware drivers in the Autounattend.xml file that rely on the Vmtools ISO being in "E:"

**Comment by Hi-Angel** [comment]
> > > @Hi-Angel - could you please take a look to see if the refactoring in #355 might have affected this behavior.
> > 
> > 
> > From what I read at the top post, it seems like the order has changed? It indeed sounds like the expected outcome [of this commit](https://github.com/hashicorp/packer-plugin-vsphere/pull/355/commits/27d5a49dcdb8ac67ec1183aa2887852034531069) _(referring at PR because all commits were squashed upon merge, so they're only distinguishable there)_.
> > I'm not quite clear though, why is that a problem. Unless I'm missing something, the plugin does not document any guarantees about the order in which ISO files will be mounted. The proper course of action on the user's side would be to fetch info after the VM got created about which disk has which ISO, and then work from there. Am I wrong here?
> 
> In [Packer docs](https://developer.hashicorp.com/packer/integrations/hashicorp/vsphere/latest/components/builder/vsphere-iso#cdrom-configuration) "_If the "iso_url" is defined in addition to the "iso_paths", the "iso_url" is added to the VM first. This keeps the "iso_url" first in the boot order by default allowing the boot iso being defined by the iso_url and the vmware tools iso added from the datastore._"
> 
> Also, there are references to VMware VM hardware drivers in the Autounattend.xml file that rely on the Vmtools ISO being in "E:"

Oh, sorry, then it is my bad for missing the documentation. I'll look at fixing it tomorrow.

**Comment by Hi-Angel** [comment]
> Will look at it tomorrow

Ha, jk. Created a fix: https://github.com/hashicorp/packer-plugin-vsphere/pull/388
