### ISSUE TITLE
v1.4.1 - error adding configuration parameters: no changes to apply

### ISSUE THREAD

**Issue by vasartori** [hashicorp/packer-plugin-vsphere#481]
When filing a bug please include the following headings, if possible. 

#### Overview of the Issue

After updating the plugin to version 1.4.1, all builds started failing.

#### Reproduction Steps

Just use provider at latest version (1.4.1)

### Packer Version
1.8.6

### Plugin Version and Builders

vsphere-iso: 1.4.1

Please select the builder.

- [x] `vsphere-iso`
- [] `vsphere-clone`

### VMware vSphere Version
8.0.3.00000

### Guest Operating System
Ubuntu 24.04

### Simplified Packer Buildfile
```source "vsphere-iso" "tks-base-image" {
  CPUs            = 2
  RAM             = 2048
  RAM_reserve_all = true

  boot_command = [
[.....]
  ]

  boot_wait            = "11s"
  cluster              = "${var.template_cluster}"
  convert_to_template  = true
  datastore            = "${var.template_datastore}"
  disk_controller_type = ["pvscsi"]
  storage {
    disk_size             = 43008
    disk_thin_provisioned = true
  }
  folder              = "${var.template_folder}"
  guest_os_type       = "ubuntu64Guest"
  insecure_connection = "true"
  iso_checksum        =...
  iso_urls            = ....
  network_adapters {
    network      = "${var.template_network}"
    network_card = "vmxnet3"
  }

  ssh_username = "${var.template_so_username}"
  ssh_password = "${var.template_so_password}"
  ssh_timeout  = "60m"

  vcenter_server = "${var.vcenter_server}"
  username       = "${var.vcenter_username}"
  password       = "${var.vcenter_password}"
  vm_name        = "${var.image_name}"

  http_content  = local.data_source_content
  http_port_min = 8080
  http_port_max = 8080

  datacenter = "${var.template_datacenter}"

}
```

### Log Fragments and `crash.log` Files
(https://gist.github.com/vasartori/bcad34cd76f0794ee54c1e3e651aa2d6)

**Comment by tenthirtyam** [comment]
Resolved in https://github.com/hashicorp/packer-plugin-vsphere/pull/483 for v1.4.2 patch release.

**Comment by tenthirtyam** [comment]
Related to https://github.com/hashicorp/packer-plugin-vsphere/pull/468.

Pushing out v1.4.2 shortly.

**Comment by tenthirtyam** [comment]
COMMUNITY NOTE

> [!IMPORTANT]  
> If you are encountering this please pin to v1.4.0. 
> Patch release v1.4.2 will release to address the error.
