### ISSUE TITLE
Add support for a `vsphere-snapshot` builder

### ISSUE THREAD

**Issue by rconde01** [hashicorp/packer-plugin-vsphere#64]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

The idea would be to start with an existing VM and snapshot name, do some configuration changes, and create a new snapshot with a selected name. 

#### Use Case(s)

Configuration steps can take a long time. Therefore, to save time it is useful to break up a large configuration where you can pick off from the last successful step on the way to full configuration. This feature would facilitate that.

You can do something similar today using vSphere-Clone and linked clones, but you end up with a bunch of vms. 

#### Potential configuration
```
vm_name
start_snapshot_name
final_snapshot_name
```

**Comment by rconde01** [comment]
Would you take a PR for this?

**Comment by rconde01** [comment]
Taking this a step further, you could do a docker style config where each config line makes a new snapshot, allowing you to always start from the last successful step.

**Comment by dbond007** [comment]
A problem with the snapshot per config line is the limited number of snapshot depth being 31. So only 31 snapshots are allowed per branch.
With the requirement here, you could do something similar using vsphere-clone. Take a snapshot at the end of each clone you do and do a thing clone from the previous, it wouldnt be in the same VM / snapshot tree, but they would be linked clones / based on the snapshots of the previous.

**Comment by tenthirtyam** [comment]
No upvotes in 2+ years. 

Closing as not planned.
