### ISSUE TITLE
Allow to specify snapshot name for create_snapshot option

### ISSUE THREAD

**Issue by rconde01** [hashicorp/packer-plugin-vsphere#65]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently when you select create_snapshot, you get a snapshot called something like "Created By Packer". It would sometimes be  useful to specify what this snapshot name should be.

#### Use Case(s)

Automation may depend on the specific snapshot name. By allowing to specify the snapshot name in these builders, it removes potentially a manual step or separate vsphere automation step.

#### Potential configuration

```
snapshot_name = "Baseline"
```

**Comment by rconde01** [comment]
Would you take a PR for this?

**Comment by sylviamoss** [comment]
Yes! We'll be more than happy to review a contribution for this 😄
