### ISSUE TITLE
vSphere-ISO unable to add Floppy to vCenter 6.7 Update 3 vm

### ISSUE THREAD

**Issue by animatco** [hashicorp/packer-plugin-vsphere#66]
Environment:
vCenter 6.7 Update 3
Packer 1.7.2

VM HW: Version 10
VM OS: Windows 2019

Issue: When a vm is spun up to create a new image, Packer is unable to mount the floppy drive.
Error Message: 2021-05-19T15:45:45-05:00: ==> vsphere-iso.windows-server: Step "StepAddFloppy" failed, aborting...

Test: Ran same HCL2 code against a vCenter 6.7 Update 1b and it works fine, but against the 6.7 Update 3.0 it fails. 

I can't seem to find anything that indicates that VMWare did anything to change how a floppy is mounted. Any help or suggestions would be appreciated.

Steve

**Comment by dbond007** [comment]
I have vCenter 6.7u3n (6.7.0.48000)
packer 1.7.2
VM version: 13
OS: Windows Server 2019 core and gui

floppy works fine. Just did a build of the 2 base images i have, has gone fine, 3 cd rom mounted and floppy, autounattend and scripts on the floppy running fine.

**Comment by animatco** [comment]
Actually going to close this as Jim McCann and Phillip Peterson found the following last week (I was on PTO).

"Well took us a bit, But my awesome vCenter Admin Phil P. rocked it out.

So changes that could effect your capability to use floppy/cd_files with packer.

vSAN encryption enabled.

If So you need to enabled these permissions.

Cryptographic operations:
Register VM
Add Disk
Clone
Direct Access
Encrypt
Encrypt New
Register VM

Hope this saves SOMEONE a lot of time. If so let use know here. "
