### ISSUE TITLE
`vsphere-iso`: Add support for SGX

### ISSUE THREAD

**Issue by amanjiofficial** [hashicorp/packer-plugin-vsphere#72]
vSphere 7.0 support hardware security virtualization using SGX. As far as I could understand packer does not support this in configuration today. Are there any plans to support this feature in packer configuration?

**Comment by sylviamoss** [comment]
Hey, thanks for open this issue. We don't have plans for supporting hardware security virtualization using SGX until now. We can totally think about supporting it. Could you tell me how do you expect it to work? For example, how would you like to configure it from our template.

**Comment by amanjiofficial** [comment]
vSphere 7 supports Intel SGX for hardware security virtualization. It can be configured when creating Virtual Machine. The initial release could have a feature to enable/disable SGX for a virtual Machine. Template can have a boolean that says `sgx_enabled` true/false.

**Comment by tenthirtyam** [comment]
There have been upvote reactions in 2.5 years.

Closing as not planned.
