### ISSUE TITLE
Index out of bounds when building vsphere images

### ISSUE THREAD

**Issue by Gnonthgol** [hashicorp/packer-plugin-vsphere#98]
Works fine in packer 1.7.2, fails in 1.7.4. Problem have been identified in this line.

https://github.com/hashicorp/packer-plugin-vsphere/blob/8b9cc236143d74ac1c26305a24c3b2d0c27c831e/post-processor/vsphere-template/step_mark_as_template.go#L131

Changing the string to either double quotes or to remove the escaped slashes fixes the problem:

    re := regexp.MustCompile(`\[(.*?)\]`)

**Comment by tierpod** [comment]
Looks like I faced the same problem

```
packer-post-processor-vsphere-template plugin: 
packer-post-processor-vsphere-template plugin: goroutine 31 [running]:
packer-post-processor-vsphere-template plugin: github.com/hashicorp/packer-plugin-vsphere/post-processor/vsphere-template.datastorePath(0xc000bf0ac0)
packer-post-processor-vsphere-template plugin:      /home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-vsphere@v1.0.1/post-processor/vsphere-template/step_mark_as_template.go:133 +0x437
packer-post-processor-vsphere-template plugin: github.com/hashicorp/packer-plugin-vsphere/post-processor/vsphere-template.(*stepMarkAsTemplate).Run(0xc000d46c00, {0x5229702, 0x28}, {0x59ac1c8, 0xc0003e77a0})
packer-post-processor-vsphere-template plugin:      /home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-vsphere@v1.0.1/post-processor/vsphere-template/step_mark_as_template.go:69 +0x3a5
```

The change was made in this commit https://github.com/hashicorp/packer-plugin-vsphere/commit/eb17fbb5603d85f4046c39bff679bca4d62a56d0#diff-90daccde26d091676affc4a2d9fb7904e389a9c8f0989c31e8d1951a20034db6

**Comment by Gnonthgol** [comment]
Problem still persists in packer 1.7.8
